spring:
  application:
    name: api-gateway
server:
  port: 10000

#传统路由
#zuul:
#  routes:
#    api:
#      path:
#        /api/**
#      url:
#        https://www.baidu.com
#    service-provider:
#      path:
#        /service-provider/**
#      url:
#        http://localhost:9001/


eureka:
  client:
    service-url:
      defaultZone:
        http://admin:admin@localhost:8000/eureka/
    enabled: false

zuul:
  routes:
    service-provider.path: /service-provider/**
    service-provider.serviceId: service-provider

service-provider:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:9001/,http://localhost:9002/
    ConnectTimeout: 1000
    ReadTimeout: 3000

hystrix:
  command:
    service-provider:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

# 暴露routes端点
management:
  endpoints:
    web:
      exposure:
        include: "*" #注意这里*要加引号，暴露全部，也可以只暴露相应endpoint
  endpoint:
    routes:
      enabled: true # 默认为true，可以省略
ribbon:
  eureka:
    enabled: false #禁用Ribbon中的Eureka支持
